version: '3.8'

services:
  app:
    build: .
    container_name: wwh-cam-server
    command: python main.py
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    ports:
      - "${CS_SERVER_PORT}:${CS_SERVER_PORT}" 