version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: local-redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PW}
    restart: unless-stopped